name: sprout_mobile_sso
description: A sample app for Sprout Mobile SSO integration

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  dartz: ^0.10.1

  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  freezed_annotation: ^1.1.0

  auto_route: 4.0.0

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_appauth: ^4.2.1
  flutter_secure_storage: ^4.2.1
  jwt_decode: ^0.3.1
  url_launcher: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.2.0
  flutter_gen: ^4.3.0
  injectable_generator: ^1.5.2
  auto_route_generator: ^4.0.0

  mockito: ^5.2.0
  bloc_test: ^9.0.3

  freezed: ^1.1.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
